#!/usr/bin/env python3
"""Generate llms-full.txt from the search index built by tools/build-search-index.py.

The output is a long markdown file grouped by type — products, services, blogs,
references, timelines, tools — listing every page with title + one-line summary.

LLM crawlers can read this single file to understand the entire site without
spidering 250+ HTML pages.
"""
import os, json
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, 'assets', 'data', 'search-index.json')
OUT  = os.path.join(ROOT, 'llms-full.txt')

GROUP_ORDER = [
    ('product',  'Products'),
    ('service',  'Services'),
    ('solution', 'Solutions'),
    ('tech',     'Technologies'),
    ('timeline', 'Standards evolution timelines'),
    ('ref',      'Engineering references'),
    ('tool',     'Engineering tools'),
    ('blog',     'Engineering blog (modern)'),
    ('archive',  'Engineering archive (2017–2025)'),
    ('category', 'Blog categories'),
    ('tag',      'Blog tags'),
    ('case',     'Case studies'),
    ('industry', 'Industries'),
    ('video',    'Videos'),
    ('brochure', 'Brochures'),
    ('engage',   'Engagement models'),
    ('about',    'About'),
    ('res',      'Resources'),
    ('contact',  'Contact'),
    ('support',  'Support'),
    ('partners', 'Partners'),
    ('trust',    'Trust'),
    ('privacy',  'Privacy'),
    ('page',     'Other'),
]

def main():
    with open(SRC) as f:
        idx = json.load(f)
    pages = idx['pages']
    groups = OrderedDict((s, []) for s, _ in GROUP_ORDER)
    for p in pages:
        s = p.get('s', 'page')
        if s not in groups:
            groups[s] = []
        groups[s].append(p)

    lines = []
    lines.append('# AmbiSecure — extended LLM-friendly site index')
    lines.append('')
    lines.append('> Full index of every indexable page on https://ambisecure.ambimat.com/.')
    lines.append('> Generated by `tools/build-llms-full.py` from the search index. Companion to [llms.txt](https://ambisecure.ambimat.com/llms.txt).')
    lines.append('')
    lines.append('Each entry is `[title](url) — one-line summary`. Summaries come from the page `<meta name="description">`. No PII is exposed; the file is regenerated whenever the site rebuilds.')
    lines.append('')

    for slug, heading in GROUP_ORDER:
        items = groups.get(slug, [])
        if not items: continue
        lines.append('## ' + heading)
        lines.append('')
        items.sort(key=lambda p: p['t'].lower())
        for p in items:
            url = 'https://ambisecure.ambimat.com' + p['u']
            title = p['t']
            desc = p.get('d', '').strip()
            if desc:
                lines.append(f'- [{title}]({url}) — {desc}')
            else:
                lines.append(f'- [{title}]({url})')
        lines.append('')

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f"wrote {OUT}: {len(pages)} pages, {os.path.getsize(OUT)} bytes")

if __name__ == '__main__':
    main()
