#!/usr/bin/env python3
"""Regenerate blog-pool.js + blog-search-index.json from blogs.json.

Source of truth: assets/data/blogs.json
Outputs:
  - assets/js/blog-pool.js              (homepage daily-spotlight rotation)
  - assets/data/blog-search-index.json  (client-side blog search)

Run after editing blogs.json. Idempotent. No external dependencies.

    python3 tools/regen-blog-pool.py
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

SRC = os.path.join(ROOT, "assets/data/blogs.json")
POOL_JS = os.path.join(ROOT, "assets/js/blog-pool.js")
SEARCH_JSON = os.path.join(ROOT, "assets/data/blog-search-index.json")

def tokenize(text):
    """Lowercase tokens, drop punctuation, keep alphanumerics + hyphens."""
    return [t for t in re.split(r"[^a-z0-9-]+", text.lower()) if t and len(t) > 1]

def main():
    with open(SRC) as f:
        data = json.load(f)
    entries = data["entries"]

    # --- blog-pool.js -------------------------------------------------------
    pool_entries = []
    for e in entries:
        # Keep only the keys blog-pool.js historically uses, in stable order.
        pool_entries.append({
            "title": e["title"],
            "url": e["url"],
            "date": e["date"],
            "summary": e["summary"],
            "categories": e.get("categories", []),
            "type": e.get("type", "modern"),
        })
    with open(POOL_JS, "w") as f:
        f.write("// AUTO-GENERATED by tools/regen-blog-pool.py — do not edit by hand.\n")
        f.write("// Source of truth: assets/data/blogs.json. Re-run that script after edits.\n")
        f.write("window.AS_BLOG_POOL = ")
        json.dump(pool_entries, f, indent=1)
        f.write(";\n")

    # --- blog-search-index.json --------------------------------------------
    # A compact searchable index. Each entry has its raw fields plus a precomputed
    # token list so the client-side search can match without re-tokenizing.
    search_entries = []
    for e in entries:
        tokens = set()
        for field in (e["title"], e["summary"]):
            tokens.update(tokenize(field))
        # Include categories and tags as tokens too (lowercase, hyphenated).
        for c in e.get("categories", []) + e.get("tags", []):
            tokens.update(tokenize(c))
        search_entries.append({
            "title": e["title"],
            "url": e["url"],
            "date": e["date"],
            "summary": e["summary"],
            "categories": e.get("categories", []),
            "tags": e.get("tags", []),
            "type": e.get("type", "modern"),
            "tokens": sorted(tokens),
        })
    with open(SEARCH_JSON, "w") as f:
        json.dump({"version": 1, "entries": search_entries}, f)

    # --- summary ------------------------------------------------------------
    all_tags = sorted({t for e in entries for t in e.get("tags", [])})
    all_cats = sorted({c for e in entries for c in e.get("categories", [])})
    print(f"OK  {len(entries)} entries  {len(all_tags)} unique tags  {len(all_cats)} unique categories")
    print(f"  -> {POOL_JS}")
    print(f"  -> {SEARCH_JSON}")

if __name__ == "__main__":
    main()
